/// Normalizer and parser for Bangladesh Prize Bond numbers and series.
/// Handles Bengali digits (০-৯) -> English digits (0-9), series extraction,
/// and regex validation for 7-digit bond serial numbers.
class DigitNormalizer {
  static const Map<String, String> _bengaliToEnglishDigits = {
    // Bengali Numerals
    '০': '0',
    '১': '1',
    '২': '2',
    '৩': '3',
    '৪': '4',
    '৫': '5',
    '৬': '6',
    '৭': '7',
    '৮': '8',
    '৯': '9',
    // Devanagari Numerals (generated by Indic OCR models)
    '०': '0',
    '१': '1',
    '२': '2',
    '३': '3',
    '४': '4',
    '५': '5',
    '६': '6',
    '७': '7',
    '८': '8',
    '९': '9',
  };

  static const Map<String, String> _englishToBengaliDigits = {
    '0': '০',
    '1': '১',
    '2': '২',
    '3': '৩',
    '4': '৪',
    '5': '৫',
    '6': '৬',
    '7': '৭',
    '8': '৮',
    '9': '৯',
  };

  /// Regex pattern to match exact 7-digit numbers without spaces.
  static final RegExp sevenDigitPattern = RegExp(r'\b\d{7}\b');

  /// Regex pattern to match 7 digits even if separated by spaces, dots or hyphens.
  static final RegExp flexibleSevenDigitPattern =
      RegExp(r'(?<!\d)(?:\d[\s\-\.]{0,2}){6}\d(?!\d)');

  /// Regex pattern to match series prefix either preceded by 'বিভাগ/সিরিজ/series'
  static final RegExp _prefixedSeriesPattern = RegExp(
    r'(?:বিভাগ|সিরিজ|series)\s*[:.-]?\s*([ক-হa-zA-Z]{1,2}(?:\s+[ক-হa-zA-Z]{1,2})?)',
    caseSensitive: false,
  );

  /// Converts any Bengali or Devanagari numerals to standard ASCII Arabic digits (0-9).
  static String toEnglishDigits(String input) {
    var result = input;
    _bengaliToEnglishDigits.forEach((bn, en) {
      result = result.replaceAll(bn, en);
    });
    return result;
  }

  /// Converts standard ASCII Arabic digits (0-9) in [input] to Bengali numerals (০-৯).
  static String toBengaliDigits(String input) {
    var result = input;
    _englishToBengaliDigits.forEach((en, bn) {
      result = result.replaceAll(en, bn);
    });
    return result;
  }

  /// Normalizes a 7-digit serial number by stripping spaces and prepending zeros if needed.
  /// Returns null if the normalized value is not exactly 7 digits.
  static String? normalizeSerial(String raw) {
    final cleaned = toEnglishDigits(raw).replaceAll(RegExp(r'\D'), '');
    if (cleaned.length == 7) {
      return cleaned;
    }
    // If length is less than 7, some people omit leading zeros (e.g., "128744" -> "0128744")
    if (cleaned.isNotEmpty && cleaned.length < 7) {
      return cleaned.padLeft(7, '0');
    }
    return null;
  }

  /// Scans [ocrRawText], normalizes all Bengali digits to English,
  /// and extracts all unique valid 7-digit prize bond numbers.
  static List<String> extractAllSerials(String ocrRawText) {
    final normalized = toEnglishDigits(ocrRawText);
    final results = <String>{};

    // First try exact 7-digit pattern
    for (final match in sevenDigitPattern.allMatches(normalized)) {
      final serial = match.group(0);
      if (serial != null && serial.length == 7) {
        results.add(serial);
      }
    }

    // Then try flexible pattern (digits separated by spaces)
    for (final match in flexibleSevenDigitPattern.allMatches(normalized)) {
      final raw = match.group(0);
      if (raw != null) {
        final digits = raw.replaceAll(RegExp(r'\D'), '');
        if (digits.length == 7) {
          results.add(digits);
        }
      }
    }

    return results.toList();
  }

  /// Scans [ocrRawText] and attempts to extract both the Series prefix and the 7-digit Serial number.
  static ScannedBondResult extractPrimaryBond(String ocrRawText) {
    final normalized = toEnglishDigits(ocrRawText);
    final allSerials = extractAllSerials(ocrRawText);

    String? foundSerial;
    String? foundSeries;

    if (allSerials.isNotEmpty) {
      // If the same 7 digits appear multiple times (as is standard on Bangladesh bonds: top and bottom),
      // we prioritize that.
      final counts = <String, int>{};
      for (final s in allSerials) {
        counts[s] = (counts[s] ?? 0) + 1;
      }
      var maxCount = 0;
      for (final entry in counts.entries) {
        if (entry.value > maxCount) {
          maxCount = entry.value;
          foundSerial = entry.key;
        }
      }
      foundSerial ??= allSerials.first;

      // Strategy 1: Look for 'বিভাগ খ শ' or 'সিরিজ কখ' or 'series KA'
      final prefixMatch = _prefixedSeriesPattern.firstMatch(ocrRawText);
      if (prefixMatch != null) {
        foundSeries = prefixMatch.group(1)?.replaceAll(RegExp(r'\s+'), ' ').trim();
      }

      // Strategy 2: Look for 'খ শ 0128744' adjacent to the found serial
      if (foundSeries == null || foundSeries.isEmpty) {
        final adjacentRegex = RegExp(
          r'([ক-হa-zA-Z]{1,2}(?:\s+[ক-হa-zA-Z]{1,2})?)\s*[-:]?\s*' + RegExp.escape(foundSerial),
          caseSensitive: false,
        );
        final adjMatch = adjacentRegex.firstMatch(normalized);
        if (adjMatch != null) {
          foundSeries = adjMatch.group(1)?.replaceAll(RegExp(r'\s+'), ' ').trim();
        }
      }
    }

    return ScannedBondResult(
      serial: foundSerial,
      series: foundSeries,
      rawText: ocrRawText,
      isValid: foundSerial != null && foundSerial.length == 7,
    );
  }

  /// Validates whether a serial number is a valid 7-digit prize bond string.
  static bool isValidSerial(String serial) {
    final normalized = toEnglishDigits(serial).trim();
    return RegExp(r'^\d{7}$').hasMatch(normalized);
  }

  /// Formats amount in BDT currency style (e.g. 600000 -> ৳৬,০০,০০০ or ৳6,00,000)
  static String formatCurrencyBDT(num amount, {bool bengali = false}) {
    // Bangladesh numbering system: lakhs and crores (e.g. 6,00,000)
    final str = amount.toInt().toString();
    String formatted;
    if (str.length <= 3) {
      formatted = str;
    } else {
      final last3 = str.substring(str.length - 3);
      var remaining = str.substring(0, str.length - 3);
      final parts = <String>[];
      while (remaining.length > 2) {
        parts.insert(0, remaining.substring(remaining.length - 2));
        remaining = remaining.substring(0, remaining.length - 2);
      }
      if (remaining.isNotEmpty) {
        parts.insert(0, remaining);
      }
      formatted = '${parts.join(',')},$last3';
    }

    final symbol = '৳';
    if (bengali) {
      return '$symbol ${toBengaliDigits(formatted)}';
    }
    return '$symbol $formatted';
  }
}

/// Represents the result of parsing OCR scanned text.
class ScannedBondResult {
  final String? serial;
  final String? series;
  final String rawText;
  final bool isValid;

  ScannedBondResult({
    this.serial,
    this.series,
    required this.rawText,
    required this.isValid,
  });

  @override
  String toString() => 'ScannedBondResult(serial: $serial, series: $series, isValid: $isValid)';
}
